- name: Oracle password playbook
  hosts: all
  tasks:
   - name: register the remote username
     become: false
     command: whoami
     changed_when: false
     register: whoami

   - name: Copy the oracle password file
     when: "'Oracle' in group_names"
     copy:
       src: /home/{{ whoami.stdout }}/oracle.passwd
       dest: /home/{{ whoami.stdout }}/oracle.passwd
       mode: '0600'
